### ISSUE TITLE
msgpackrpc.error.TransportError: Retry connection over the limit

### ISSUE THREAD

**Issue by ninamoello** [nikhil-sethi/xflrpy#1]
Trying to run the test example (A brief sketch) on macOS 12.3.1
I have quoted the exact error log bellow. Any help or a hint would be appreciated.

WARNING:tornado.general:Connect error on fd 7: ECONNREFUSED
WARNING:tornado.general:Connect error on fd 7: ECONNREFUSED
WARNING:tornado.general:Connect error on fd 7: ECONNREFUSED
WARNING:tornado.general:Connect error on fd 7: ECONNREFUSED
WARNING:tornado.general:Connect error on fd 7: ECONNREFUSED
Traceback (most recent call last):
  File "/Users/ninamoello/PycharmProjects/xflr/testxlfr.py", line 8, in <module>
    xp = xflrClient(connect_timeout=100)
  File "/Users/ninamoello/PycharmProjects/xflr/venv/lib/python3.8/site-packages/xflrpy/client.py", line 14, in __init__
    if self.ping():
  File "/Users/ninamoello/PycharmProjects/xflr/venv/lib/python3.8/site-packages/xflrpy/client.py", line 37, in ping
    return self._client.call("ping")
  File "/Users/ninamoello/PycharmProjects/xflr/venv/lib/python3.8/site-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()
  File "/Users/ninamoello/PycharmProjects/xflr/venv/lib/python3.8/site-packages/msgpackrpc/future.py", line 43, in get
    raise self._error
msgpackrpc.error.TransportError: Retry connection over the limit

Process finished with exit code 1

**Comment by nikhil-sethi** [comment]
Hey @ninamoello. Thanks for raising this issue. It looks like the server (i.e. xflServer) is not running on the cpp side.
Here are some of my thoughts as to why this could be.
1. You forgot to run the actual xflrpy software (i.e. the binary). If this is the case, then just run that first, and then try running the client script (testxflr.py)
2. I'm currently using port 8080 to establish the server-client connection. This is a relatively small number and operating systems like Windows often reserve smaller ports for their own esoteric exchanges. If this is the case with mac as well, just change this port to a high value (eg: 20000) on both the [client](https://github.com/nikhil-sethi/xflrpy/blob/e67180b4a42e7e9945fd8eec38098e691b449ae8/PythonClient/xflrpy/client.py#L11) and [server](https://github.com/nikhil-sethi/xflrpy/blob/e67180b4a42e7e9945fd8eec38098e691b449ae8/xflr5v6/globals/main.cpp#L188) side, recompile, and test it again.

Unfortunately, I don't have a mac with me to test these out. So you'll have to help me out here! Let me know how it goes.

**Comment by nikhil-sethi** [comment]
Hey @ninamoello 
I hope the problem was solved. Closing the issue for now. Feel free to reopen it.
