### ISSUE TITLE
how to do 3D wings analysis?

### ISSUE THREAD

**Issue by HYB777** [nikhil-sethi/xflrpy#2]
how to do 3D wings analysis if I already have 2D airfoil section?

**Comment by nikhil-sethi** [comment]
Hey. As of yet, 3D wing analysis is only possible in the 'pythonqt' branch. I plan to add basic 3D analysis to the master branch very soon though!

**Comment by nikhil-sethi** [comment]
Hey @HYB777. 3D wing analysis is now supported on the master branch. Let me know if you face some trouble with it. Closing the issue for now
