### ISSUE TITLE
Hello, can you share the code for BetaFlight AirSim?

### ISSUE THREAD

**Issue by Tom920706** [nikhil-sethi/xflrpy#6]
Hello, author, can you share a code for using BetaFlight with AirSim? Thank you

**Comment by nikhil-sethi** [comment]
Hey @Tom920706,
Please avoid creating issues in this repository that are not related.
But to answer your question: the betaflight + airsim link is at [this](https://github.com/nikhil-sethi/betaflight/tree/airsim-sitl) link. Note that it's something I worked on very long ago and it might be out of date. Best of luck.

Closing the issue.
